FROM us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:latest

WORKDIR /app

ARG MODEL_VERSION_ARG
ARG PROJECT_ID_ARG

ENV PYTHONUNBUFFERED=1
ENV MODEL_VERSION=$MODEL_VERSION_ARG
ENV GOOGLE_CLOUD_PROJECT=$PROJECT_ID_ARG

COPY requirements-vllm.txt .

RUN pip install --no-cache-dir \
    --index-url https://pypi.org/simple \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org \
    -r requirements-vllm.txt

COPY . .
ENTRYPOINT ["sh", "-c", "python vllm_serve.py --model-version ${MODEL_VERSION}"]