FROM nvcr.io/nvidia/tritonserver:25.08-trtllm-python-py3

RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gnupg \
    curl \
  && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
     gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg \
  && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] \
     https://packages.cloud.google.com/apt cloud-sdk main" \
     > /etc/apt/sources.list.d/google-cloud-sdk.list \
  && apt-get update && apt-get install -y google-cloud-cli \
  && rm -rf /var/lib/apt/lists/*

ENV LOCAL_CHECKPOINT_DIR=/tmp/trtllm_checkpoint
ENV LOCAL_MODEL_DIR=/tmp/trtllm_engines
ENV LOCAL_HF_DIR=/tmp/hf_model_files

COPY ci/build_triton_entrypoint_tp.sh /build_triton_entrypoint_tp.sh
RUN chmod +x /build_triton_entrypoint_tp.sh

ENTRYPOINT ["/build_triton_entrypoint_tp.sh"]