models:
  llama-3.2-pytorch:
    id: "meta-llama-Llama-3.2-3B-Instruct"
    image:
      repository-name: 'inference-repository'
      image-name: 'inference-image'
      dockerfile: 'Dockerfile.pytorch'
    registry-id:
      europe-west3: '8270003096596250624'
    storage:
      bucket: 'gcp-ml-models'
      relative-path: 'meta-llama-Llama-3.2-3B-Instruct'
    endpoint:
      name: 'Fastapi-llama3.2-3b-pytorch'
      id: '3631838639148761088'
      is-dedicated: true
      name: predict
    inference:
      max_model_length: 2048
      max_new_tokens: 600
  llama-3.2-vllm:
    id: "meta-llama-Llama-3.2-3B-Instruct"
    image:
      repository-name: 'inference-repository'
      image-name: 'vllm-image'
      dockerfile: 'Dockerfile.vllm'
    registry-id:
      europe-west3: '3698286524861775872'
    storage:
      bucket: 'gcp-ml-models'
      relative-path: 'meta-llama-Llama-3.2-3B-Instruct'
    endpoint:
      name: 'Fastapi-llama3.2-3b-vllm'
      id: '5339547322852311040'
      is-dedicated: true
      name: predict
    inference:
      max_model_length: 2048
      max_new_tokens: 512
  llama-3.2-trtllm:
    id: "meta-llama-Llama-3.2-3B-Instruct"
    image:
      repository-name: 'inference-repository'
      image-name: 'trtllm-image'
      dockerfile: 'Dockerfile.trtllm'
    registry-id:
      europe-west3: '4207219671033708544'
      europe-west4: '5420348233354313728'
      europe-west2: '2862508154170638336'
    storage:
      bucket: 'gcp-ml-models'
      relative-path: 'trtllm-engine/meta-llama-Llama-3.2-3B-Instruct'
      hf-relative-path: 'meta-llama-Llama-3.2-3B-Instruct'
    endpoint:
      name: 'Triton-llama3.2-3b-trt-llm'
      id: 
        europe-west3: '4081969903467233280'
        europe-west4: '5106279333949865984'
        europe-west2: '9133882785470087168'
      is-dedicated: true
      name: /v2/models/tensorrt_llm_bls/generate_stream
    inference:
      max_model_length: 2048
      max_new_tokens: 512
      inference_batch_size: 64
      tensor_parallel: 2
      num_gous: 2
trtllm-build:
  image:
    repository-name: 'trt-build-repository'
    image-name: 'trtllm-builder-image'
    dockerfile: 'Dockerfile.trtllm.dev'
  storage:
    bucket: 'gcp-ml-models'
    relative-path: 'meta-llama-Llama-3.2-3B-Instruct'
compute:
  l4x2:
    machine_type: 'g2-standard-24'
    accelerator_type: 'nvidia-l4'
    n_accelerators: 2
  l4:
    machine_type: 'g2-standard-8'
    accelerator_type: 'nvidia-l4'
    n_accelerators: 1
  v100-small:
    machine_type: 'n1-standard-4'
    accelerator_type: 'nvidia-tesla-v100'
  v100:
    machine_type: 'n1-standard-8'
    accelerator_type: 'nvidia-tesla-v100'
  a100-40g:
    machine_type: 'a2-highgpu-1g'
    accelerator_type: 'nvidia-tesla-a100'
  a100-40g:
    machine_type: 'a2-ultragpu-1g'
    accelerator_type: 'nvidia-a100-80gb'
